// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfidAPI.Data;

namespace RfidAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210727144037_db")]
    partial class db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("RfidAPI.Models.Team", b =>
                {
                    b.Property<int?>("teamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("teamInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("teamName")
                        .HasColumnType("TEXT");

                    b.Property<string>("teamQQ")
                        .HasColumnType("TEXT");

                    b.HasKey("teamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RfidAPI.Models.TeamUser", b =>
                {
                    b.Property<string>("TeamUserID")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<int>("level")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamUserID");

                    b.ToTable("TeamUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
